version: "3"
services:
  server:
    image: bia-local:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BIA_API_URL: http://localhost:3001
    ports:
      - 3001:8080
    links:
      - database
    environment:
      DB_USER: postgres
      DB_PWD: postgres
      DB_HOST: database
      DB_PORT: 5432
  database:
    image: postgres:13.7
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=bia"
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
